name: ci

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Should generate USAGE.md for tf11_basic
        with:
          working-dir: examples/tf11_basic
          output-file: USAGE.md
          template: |-
            <!-- BEGIN_TF_DOCS -->
            # Test tf11 basic
            ## Verify
            Should use the template defined instead of the default
            Should inject the table under usage
            # Usage
            {{ .Content }}
            <!-- END_TF_DOCS -->
          indention: 3
