name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Should generate USAGE.md for tf11_basic
        with:
          output-file: USAGE.md
          template: |-
            <!-- BEGIN_TF_DOCS -->
            # Test tf11 basic
            ## Verify
            Should use the template defined instead of the default
            Should inject the table under usage
            # Usage
            {{ .Content }}
            <!-- END_TF_DOCS -->
          indention: 3
