name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Should generate USAGE.md for tf11_basic
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          working-dir: .
          output-file: README.md
          config-file: .terraform-docs.yml
          git-push: "true"
          output-method: inject
