name: Generate terraform docs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Should generate USAGE.md for tf11_basic
        uses: ./
        with:
          working-dir: examples/tf11_basic
          output-file: USAGE.md
          template: |-
            <!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
            {{ .Content }}
            <!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
          indention: 3