name: terraform-aws-acm
'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to other repositories
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: aws/terraform-aws-acm/
          destination-github-username: 'tomarv2'
          destination-repository-name: 'terraform-aws-acm'
          user-email: varuntomar2019@gmail.com
          commit-message: Sync from management repo
          target-branch: develop
